# Generated by Django 5.1.7 on 2025-05-12 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_grao'),
    ]

    operations = [
        migrations.AddField(
            model_name='grao',
            name='categoria',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='graos', to='core.categoria'),
        ),
        migrations.AddField(
            model_name='produto',
            name='grao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='core.grao'),
        ),
    ]
