# Generated by Django 5.1.7 on 2025-05-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_endereco_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='cep',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='numero',
            field=models.IntegerField(),
        ),
    ]
