# Generated by Django 5.2.1 on 2025-09-02 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_produto_categoria_produto_categoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
